apiVersion: v2
name: metget-server
description: A deployment of the metget-server instance
type: application
version: 0.6.0
appVersion: "0.6.0"
icon: https://raw.githubusercontent.com/waterinstitute/metget-server/main/img/MetGet_logo_square.png
