apiVersion: v2
name: metget-server
description: A deployment of the metget-server instance
type: application
version: 0.7.2
appVersion: "0.7.2"
icon: https://raw.githubusercontent.com/waterinstitute/metget-server/main/img/MetGet_logo_square.png
